config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as rooms_views

app_name = "core"

urlpatterns = [
    path("", rooms_views.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path(
        "update-password/", views.UpdatePasswordView.as_view(), name="update-password"
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path(
        "<int:pk>/conversations",
        views.ConversationListView.as_view(),
        name="conversations",
    ),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
]

users/models.py
import uuid
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.mail import send_mail
from django.conf import settings
from django.utils.html import strip_tags
from django.template.loader import render_to_string
from django.shortcuts import reverse
from core import managers as core_managers
from django.contrib.auth.models import UserManager


class CustomModelManager(UserManager):
    def get_or_none(self, **kwargs):
        try:
            return self.get(**kwargs)
        except self.model.DoesNotExist:
            return None


class User(AbstractUser):

    """Custom User Model"""

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OTHER = "other"
    GENDER_CHOICE = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
        (GENDER_OTHER, "Other"),
    )

    LANGUAGE_ENGLISH = "en"
    LANGUAGE_KOREAN = "kr"
    LANGUAGE_CHOICE = (
        (LANGUAGE_ENGLISH, "English"),
        (LANGUAGE_KOREAN, "Korean"),
    )

    CURRENCY_USD = "usd"
    CURRENCY_KRW = "krw"
    CURRENCY_CHOICE = (
        (CURRENCY_USD, "USD"),
        (CURRENCY_KRW, "KRW"),
    )

    LOGIN_EMAIL = "email"
    LOGIN_GITHUB = "github"
    LOGIN_KAKAO = "kakao"
    LOGIN_CHOICE = (
        (LOGIN_EMAIL, "Email"),
        (LOGIN_GITHUB, "Github"),
        (LOGIN_KAKAO, "Kakao"),
    )

    avatar = models.ImageField(upload_to="avatars", blank=True)
    gender = models.CharField(choices=GENDER_CHOICE, max_length=10, blank=True)
    bio = models.TextField(blank=True)
    birthdate = models.DateField(blank=True, null=True)
    language = models.CharField(
        choices=LANGUAGE_CHOICE, max_length=2, blank=True, default=LANGUAGE_KOREAN
    )
    currency = models.CharField(
        choices=CURRENCY_CHOICE, max_length=3, blank=True, default=CURRENCY_KRW
    )
    superhost = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)
    email_secret = models.CharField(max_length=20, default="", blank=True)
    login_method = models.CharField(
        max_length=80, choices=LOGIN_CHOICE, default=LOGIN_EMAIL
    )

    objects = CustomModelManager()

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

    def verify_email(self):
        if self.email_verified is False:
            secret = uuid.uuid4().hex[:20]
            self.email_secret = secret
            html_message = render_to_string(
                "emails/verify_email.html", {"secret": secret}
            )
            send_mail(
                "Verify Airbnb Account",
                strip_tags(html_message),
                settings.EMAIL_FROM,
                [self.email],
                fail_silently=False,
                html_message=html_message,
            )
            self.save()
        return

users/forms.py
from django import forms
from . import models


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is wrong"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User does not exist"))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("first_name", "last_name", "gender", "email")
        widgets = {
            "first_name": forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
            "email": forms.EmailInput(attrs={"placeholder": "Email Name"}),
        }

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"})
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError(
                "That email is already taken", code="existing_user"
            )
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("Password confirmation does not match")
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()

users/views.py
import os
import re
from config import settings
from django.http import HttpResponse
import requests
from django.views import View
from django.views.generic import FormView, DetailView, UpdateView
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.core.files.base import ContentFile
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.utils import translation
from . import forms, models, mixins
from reviews import forms as review_form
from conversations import models as conv_models


class LoginView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg == None:
            return reverse("core:home")
        else:
            return next_arg


def log_out(request):
    messages.info(request, f"Bye {request.user.first_name}, see you soon")
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")
    # initial = {
    #     "first_name": "Kyeyeop",
    #     "last_name": "Kim",
    #     "email": "kky8822@gmail.com",
    # }

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        user.verify_email()
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
        # to do: success message
    except models.User.DoesNotExist:
        # to do: add error message
        pass

    return redirect(reverse("core:home"))


def github_login(request):
    client_id = os.environ.get("GH_ID")
    redirect_uri = "http://airbnb-clone.eba-qspghbag.ap-northeast-2.elasticbeanstalk.com/users/login/github/callback"
    return redirect(
        f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user,user:email"
    )


class GithubException(Exception):
    pass


def github_callback(request):
    try:
        client_id = os.environ.get("GH_ID")
        client_secret = os.environ.get("GH_SECRET")
        code = request.GET.get("code", None)

        if code is not None:
            result = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
            )
            result_json = result.json()
            error = result_json.get("error", None)
            if error is not None:
                raise GithubException("Can not get Github token")
            else:
                access_token = result_json.get("access_token")
                profile_request = requests.get(
                    "https://api.github.com/user",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                profile_json = profile_request.json()
                email_request = requests.get(
                    "https://api.github.com/user/emails",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                email_json = email_request.json()
                username = profile_json.get("login", None)
                if username is not None:
                    name = profile_json.get("name")
                    email = email_json[0].get("email")
                    bio = profile_json.get("bio")
                    avatar_url = profile_json.get("avatar_url")

                    if bio is None:
                        bio = ""
                    try:
                        user = models.User.objects.get(email=email)
                        admin = models.User.objects.get(
                            email=os.environ.get("ADMIN_EMAIL")
                        )
                        if user.login_method != models.User.LOGIN_GITHUB:
                            if user == admin:
                                login(request, user)
                                return redirect(reverse("core:home"))
                            else:
                                raise GithubException(
                                    f"please log in with {user.login_method}"
                                )
                    except models.User.DoesNotExist:
                        user = models.User.objects.create(
                            email=email,
                            email_verified=True,
                            first_name=name,
                            username=email,
                            bio=bio,
                            login_method=models.User.LOGIN_GITHUB,
                        )
                        user.set_unusable_password()
                        user.save()
                        if avatar_url is not None:
                            photo_request = requests.get(avatar_url)
                            user.avatar.save(
                                f"{name}-avatar", ContentFile(photo_request.content)
                            )
                    login(request, user)
                    messages.success(request, f"Welcome Back {user.first_name}")
                    return redirect(reverse("core:home"))
                else:
                    raise GithubException("Can not get user information from Gihub API")
        else:
            raise GithubException("Can not get Github code")

    except GithubException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


def kakao_login(request):
    REST_API_KEY = os.environ.get("KAKAO_ID")
    REDIRECT_URI = "http://airbnb-clone.eba-qspghbag.ap-northeast-2.elasticbeanstalk.com/users/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={REST_API_KEY}&redirect_uri={REDIRECT_URI}&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    try:
        # raise KakaoException("Test Kakao auth error")
        code = request.GET.get("code")
        REST_API_KEY = os.environ.get("KAKAO_ID")
        REDIRECT_URI = "http://airbnb-clone.eba-qspghbag.ap-northeast-2.elasticbeanstalk.com/users/login/kakao/callback"
        token_request = requests.post(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={REST_API_KEY}&redirect_uri={REDIRECT_URI}&code={code}"
        )
        token_json = token_request.json()
        error = token_json.get("error", None)
        if error is not None:
            raise KakaoException("Can not get Kakao token")
        access_token = token_json.get("access_token")
        profile_request = requests.get(
            "https://kapi.kakao.com//v2/user/me",
            headers={
                "Authorization": f"Bearer {access_token}",
                "Accept": "application/json",
            },
        )
        profile_json = profile_request.json()
        kakao_account = profile_json.get("kakao_account")
        email = kakao_account.get("email", None)
        profile = kakao_account.get("profile")
        nickname = profile.get("nickname", None)
        avatar_url = profile.get("profile_image_url", None)
        if email is None:
            raise KakaoException("Can not get user information from Kakao API")
        try:
            user = models.User.objects.get(email=email)
            admin = models.User.objects.get(email=os.environ.get("ADMIN_EMAIL"))
            if user.login_method != models.User.LOGIN_KAKAO:
                if user == admin:
                    login(request, user)
                    return redirect(reverse("core:home"))
                else:
                    raise KakaoException(f"Please log in with {user.login_method}")
        except models.User.DoesNotExist:
            user = models.User.objects.create(
                email=email,
                email_verified=True,
                first_name=nickname,
                username=email,
                login_method=models.User.LOGIN_KAKAO,
            )
            user.set_unusable_password()
            user.save()
            if avatar_url is not None:
                photo_request = requests.get(avatar_url)
                user.avatar.save(
                    f"{nickname}-avatar", ContentFile(photo_request.content)
                )

        login(request, user)
        messages.success(request, f"Welcome Back {user.first_name}")
        return redirect(reverse("core:home"))
    except KakaoException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


class UserProfileView(mixins.LoggedInOnlyView, DetailView):
    model = models.User
    context_object_name = "user_obj"
    form_class = review_form.CreateReviewForm

templates/users/login.html
{% extends "base.html" %}

{% block header %}
  {% include "mixins/header.html" with searchbar="False" %}    
{% endblock header %}

{% block page_title %}Login{% endblock page_title %}

{% block contents %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'partials/social_login.html' %}        

        {% include 'mixins/auth/auth_form.html' with form=form cta="Log in" %}

        <div class="mt-5">
            <span class="mr-2">Don't have an account?</span>
            <a href="{% url 'users:signup' %}" class="text-teal-500 font-medium">Sign up</a>
        </div>
    </div>    
{% endblock contents %}

templates/users/signup.html
{% extends "base.html" %}

{% block header %}
  {% include "mixins/header.html" with searchbar="False" %}    
{% endblock header %}

{% block page_title %}Sing up{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block contents %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'partials/social_login.html' %}

        {% include 'mixins/auth/auth_form.html' with form=form cta="Sign up" %}

        <div class="mt-5">
            <span class="mr-2">Have an account?</span>
            <a href="{% url 'users:login' %}" class="text-teal-500 font-medium">Log in</a>
        </div>

    </div>
    
{% endblock contents %}

templates/users/update-password.html
{% extends "base.html" %}

{% block header %}
  {% include "mixins/header.html" with searchbar="False" %}    
{% endblock header %}

{% block page_title %}Update Password{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block contents %}

<div class="h-75vh">
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/auth/auth_form.html' with form=form cta="Update Password" %}

    </div>
</div>
    
{% endblock contents %}

templates/users/update-profile.html
{% extends "base.html" %}

{% block header %}
  {% include "mixins/header.html" with searchbar="False" %}    
{% endblock header %}

{% block page_title %}Update Profile{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block contents %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/auth/auth_form.html' with form=form cta="Update Profile" %}

        {% if object.login_method == "email" %}
            <div class="mt-5">
                <a href="{% url 'users:update-password' %}" class="text-teal-500 font-medium">Change Password</a>
            </div>            
        {% endif %}
            
    </div>
    
{% endblock contents %}

templates/users/user_detail.html
{% extends "base.html" %}

{% block header %}
  {% include "mixins/header.html" with searchbar="True" %}    
{% endblock header %}

{% block page_title %}{{user.first_name}}'s Profile{% endblock page_title %}
    
{% block contents %}
    <div class="min-h-screen">
        <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

            {% include 'mixins/user_avatar.html' with user=user_obj %}
                
            <div class="flex items-center">
                <span class="text-3xl mt-1">{{user_obj.first_name}}</span>
                {% if user_obj.superhost %}
                    <i class="fas fa-check-circle text-teal-400 text-lg ml-1"></i>
                {% endif %}
            </div>
            
            <span class="text-lg mb-5">{{user_obj.bio}}</span>
    
            {% if user == user_obj %}
                <a href="{% url 'users:update' %}" class="btn-link bg-red-500">Edit Profile</a>            
            {% endif %}
    
            {% comment %} {{user.username}}
            {{user.first_name}}
            {{user.last_name}} {% endcomment %}
            
            {% comment %} {{hello}} {% endcomment %}
            
        </div>
        
        {% if user_obj.rooms.count > 0 %}
            <div class="container flex flex-col items-center mx-auto pb-10">
                <h3 class="mb-12 text-2xl">{{user_obj.first_name}}'s Rooms</h3>
                <div class="flex flex-wrap mb-10 w-full">
                    {% for room in user_obj.rooms.all %}
                        {% include 'mixins/room_card.html' with room=room %}
                    {% endfor %}
                </div>
            </div>        
        {% endif %}

        {% if user_obj == user and user_obj.reservations.count > 0 %}
            <div class="container flex flex-col items-center mx-auto pb-10">
                <h3 class="mb-12 text-2xl">{{user_obj.first_name}}'s Reservations</h3>

                {% for reservation in user_obj.reservations.all %}
                    {% include "mixins/reservation/reservation_card.html" with reservation=reservation form=form%}
                {% endfor %}
            </div>        
        {% endif %}
    </div>

{% endblock contents %}